import Layout from "@/components/layout/layout"
import NextAuthProvider from "@/providers/NextAuthProvider"
import { yekan } from "@/utils/font"

export const metadata = {
  title: 'پروژه املاک',
  description: 'Generated by MortezaKia',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  )
}
