import DashboardSidebar from "@/components/layout/DashboardSidebar";
import {getServerSession} from 'next-auth'
import { authOptions } from "../api/auth/[...nextauth]/route";
import {redirect} from 'next/navigation'
import ConncetToDb from "@/utils/ConnectToDb";
import User from "@/models/User";

export const metadata = {
  title: 'پنل کاربری',
  description: 'Generated by mortezaKia',
}

export default async function layout({children}) {
  const session = await getServerSession(authOptions)
  if(!session) redirect('/SignIn')
  await ConncetToDb()
  const user = await User.findOne({email:session.user.email})
  if(!user) return(<h3>مشکلی پیش آمده است</h3>)
  return (
    <div>
      <DashboardSidebar role={user.role} email={session.user.email}>
        {children}
      </DashboardSidebar>
    </div>
  )
}
